import "@rainbow-me/rainbowkit/styles.css";
import type { Metadata } from "next";
import Navbar from "../components/navbar";
import "./globals.css";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className="dark relative flex min-h-screen w-full flex-col items-center bg-gray-950 leading-6 text-white">
            <div className="bg-radial-gradient-master absolute left-1/2 top-0 -z-10 block h-screen w-full -translate-x-1/2"></div>
            <Navbar />
            {children}
         </body>
      </html>
   );
}
